# Generated by Django 5.2 on 2025-04-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bic',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
    ]
