# Generated by Django 5.2 on 2025-06-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
        ('news', '0002_alter_news_options_alter_news_image'),
    ]

    operations = [
    ]
