# Generated by Django 5.2 on 2025-05-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True)),
                ('clicked_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_address', models.TextField(blank=True, null=True)),
                ('estimated_realization_date', models.DateField(blank=True, null=True)),
                ('bulding_type', models.CharField(blank=True, max_length=255, null=True)),
                ('building_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('cac_system_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cac_idu_type', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity_per_m2', models.CharField(blank=True, max_length=255, null=True)),
                ('piping_type', models.CharField(blank=True, max_length=255, null=True)),
                ('odu_placing', models.CharField(max_length=255)),
                ('accessories', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], max_length=20)),
                ('file_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
