# Generated by Django 5.2 on 2025-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_bulding_type_order_building_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building_floors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='estimated_realization_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
