# Generated by Django 5.2 on 2025-04-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='product.product'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='product.type')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productmodel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
