# Generated by Django 5.2 on 2025-04-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_model_description_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
