# Generated by Django 5.2 on 2025-04-12 17:43

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_image_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', default=0, on_delete=django.db.models.deletion.CASCADE, to='product.type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='type', chained_model_field='type', on_delete=django.db.models.deletion.CASCADE, to='product.productmodel'),
        ),
    ]
